### PR TITLE
make sonos-http-api "express" compatible

### PR DESCRIPTION
**Pull request by cederigo**
Hi, I wanted to use your api inside my express application so I made the following changes + some minor fixes (state action). cheers Cédric

### CODE REVIEW

**Comment by jishi** [comment]
Hi, thanks for contributing. 

The express support is a nice adjustment, but I'm not sure how I feel about the customActions modification. My idea was that you would just drop an extra file in the actions directory if you needed something custom. The way you added it, a custom dir would effectively disable all the builtin actions, correct? That feels kind of confusing. 

Could you provide a user scenario where the custom directory makes sense, and becomes a necessity?

**Comment by cederigo** [comment]
Hi

Nice to hear that you like the express support. My use case for the custom
actions is as follows:
 - I mounted the api in my express app as /sonos.
 - Now I want to override the existing favorites action, so I specify my
actions dir (ex. routes/sonos/actions) and implement a new favorites.js
action. I registered it under the same name so the built in action is
overridden. Now I have all built in actions *but* my favorites
implementation.
 - I also implemented a queue action in the same directory.

So, if a custom actions dir is specified the builtin actions are *not*
disabled but extended. Or overridden if I register my action under an
existing name. What do you think?

cheers, Cédric

**Comment by excentris** [comment]
I was planning on implementing the express support myself for a project I am working on and I just saw that somebody had already done it. Great!
@cederigo Could you open a new pull request with just the express support and maybe start a new discussion for the customActions?

**Comment by jishi** [comment]
I'm fine with merging the express support if you can isolate that, no problem.

**Comment by excentris** [comment]
@cederigo Could you do that? Or do you want me to do it?

**Comment by cederigo** [comment]
Ola, sorry i was busy doing other things. I'll do it tomorrow. Cheers

**Comment by cederigo** [comment]
Ok like this? cheers

**Comment by excentris** [comment]
That was fast! Thank you very much!

**Comment by excentris** [comment]
@jishi are you still open to merge the express support? Thanks in advance!

**Comment by jishi** [comment]
Yes, I was just busy. Here you go, let me know if there is any problem with it (I'm not very familiar with express yet).

**Comment by excentris** [comment]
Thanks! I'll check it out this weekend.

**Comment by martin0852** [comment]
@cederigo I am just dipping my feet into this as I only got my SONOS at christmas so would appreciate it if you could give some guidance on how exactly to integrate this into existing express project? 

I am currently running an express server and running this api from a separate node server so it would make a lot of sense to merge and you seem to be the guy to ask from this issue. Any help appreciated.
M

**Comment by cederigo** [comment]
Hi @martin0852 

What you need to do in your express app.

First init the sonos http api:
```javascript
const SonosHttpAPI = require('./lib/sonos-http-api.js');
const SonosSystem = require('sonos-discovery');

var settings = require('./settings'); // Copy from https://github.com/jishi/node-sonos-http-api/blob/master/settings.js
const discovery = new SonosSystem(settings);
const sonosApi = new SonosHttpAPI(discovery, settings);
```
Afterwards you can mount `api.requestHandler` on your router where you want to. Ex:
```javascript
router.get('/sonos', sonosApi.requestHandler);
```
Hope this helps. Cheers Cédric

**Pull request merged**
