### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by riemers**
Now with node:slim as base.

### CODE REVIEW

**Comment by jishi** [comment]
You don't have to initiate new pull request for each change, you can just push the changes to the branch that you initiated the pull request from I think.

Some questions:

Is the EXPOSE necessary when you run --net=host ?
Usually you prepare the filesystem in the image preparation, and not on docker runtime. I guess you did the opposite because of the image cache, correct?
If you invoke docker run with --restart="always", then I think pm2 would be redundant. It would always restart and the node process would always output the logs. What do you think? Would you be able to test that?

**Comment by riemers** [comment]
Yeah i looked at adding the changes to the current PR but could not find it.. the EXPOSE is not really needed inded, its just an indication so that people know what ports it might use (in case of already in use) although they would see it when they start up. The thing with restart allways is that it restarts the complete container as far as i know. pm2 only restarts the process. That means that everytime docker sees it dying, it start up and does a git clone. Not that it is the end of the world, but also not the best perhaps ;)

So how about remove EXPOSE, since we assume people know what they are doing with --net and i could do the restart always unless you agree that downloading the repo each time it fails is a problem. (docker does throttle if it keeps restarting, so it wont be a cpu hog anyways)

**Comment by riemers** [comment]
I see my changes now, last time i must have overlooked that on the other PR :+1:

**Comment by jishi** [comment]
You are right that the repo download is an issue with restart, so it is probably better to use pm2 for now. If I start tagging releases of the http api, we could probably also keep a versioning scheme for the docker repository as well, with prepared docker containers instead, which is probably a more "normal" approach.

I have had plans to create a pre-compiled .img for the raspberry pi that has both the http api and the web controller, maybe we could consider doing the same for a docker instance?

**Comment by riemers** [comment]
Well the restart always does throttling, so it wont be 24/7 downloads of github. If you mean a .img for the PI just to do this single task i don't think people would do that, since they can run more then only that on the PI.

**Comment by jishi** [comment]
Well, the target group would be persons that think the installation process is to complex and just want to flash an sd-card and boot it up.

**Comment by riemers** [comment]
If you buying a Pi, i would expect some form of intelligence ;) but you got a point there.

**Pull request merged**
