### PR TITLE
Added playlists request module

### PR DESCRIPTION
**Pull request by mattnewham**
Added the playlists.js file which operates in the same way as favorites.js but returns available playlists instead.

Required for https://github.com/jishi/node-sonos-discovery/pull/59 

You can visit http://localhost:5005/playlists to pull a JSON list of available playlists

### CODE REVIEW

**Comment by jishi** [comment]
This is already part of beta though...

**Comment by mattnewham** [comment]
Hey Jimmy

I thought you'd said that presets weren't working in the beta yet?!

**Comment by jishi** [comment]
No, presets should work, byt say/sayAll does not. But I was referring to the possibility to list playlists.

**Comment by noesberger** [comment]
Hi

I tried with 1.0.0-beta.17 and I'm not able to apply a playlist to preset.json.
If I try with "playlist":"Test_Andreas", it's just ignoring the entry.
If I try with "favorite":"Test_Andreas", I'm getting the following error - {"status":"error","error":"Error: Favorite not found\n    at /home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithFavorite.js:21:15\n    at process._tickCallback (node.js:366:9)"}

What I'm doing wrong?

**Comment by jishi** [comment]
Yeah, no playlist support is not implemented in presets yet. I thought it was, but checked the source and it wasn't.

**Comment by noesberger** [comment]
I tried now a workarround.
I've created a new branch on my fork: https://github.com/noesberger/node-sonos-discovery/tree/playlist

This is your Beta 17 Code and then I just added the replaceWithPlaylist.js and modified the code in applyPreset.js to check as well for a Playlist.
The replaceWithPlaylist.js is from your master branch with some little changes, I had to call playlist.items and not only playlist.

**Pull request merged**
