### PR TITLE
Add BBC Sounds service

### PR DESCRIPTION
**Pull request by tomslominski**
I'm not sure if you want to go down the road of adding a separate action for every service Sonos supports, but I needed this and I thought somebody else might find this useful too.

### CODE REVIEW

**Comment by jishi** [comment]
I don't mind adding additional services, but please add some documentation as well for how to use it (and find out how to reference different streams), and I will merge it.

**Comment by ashenshugarRET** [comment]
I would be happy to contribute the required documentation as I too find this service addition really helpful. Please can you confirm how best I can do this?

In case you'd like to simply change the README.md file as you merge the pull request, below is a file with the text explaining how to use the BBC Sounds service with node-sonos-http-api and a table of the available streams I created from the link in @tomslominski linked to in his code.

[BBC Sounds station codes.txt](https://github.com/jishi/node-sonos-http-api/files/8248028/BBC.Sounds.station.codes.txt)

**Comment by jishi** [comment]
It would be great if it could be included in the PR (or a subsequent PR for that matter). Just clicking merge is zero effort for me :)

**Comment by ashenshugarRET** [comment]
Great, I've just created the required PR

**Pull request merged**
