### PR TITLE
184: Add config and param for say/sayAll

### LINKED ISSUE #184: Feature request: Configuration value for `say`/`sayAll` volume
I looked in the say.js and noticed that the `announceVolume` is statically set to 40 and isn't configurable.

### PR DESCRIPTION
**Pull request by tdlm**
- Fixes #184 
- Allowing configuration for say/sayAll volume default
- Allowing for parameter-based override for volume

### CODE REVIEW

**Comment by tdlm** [comment]
@jishi Please #reviewmerge

**Comment by jishi** [comment]
Could you please update the README as well with the new info? That would be great, then I can just auto-merge this.

**Comment by JohnyJaknove** [comment]
I have notifications off for this tread but I'm still getting messages, anybody know why?

**Comment by jishi** [comment]
This is part of beta now, with updated documentation.

**Pull request closed without merging**
