### PR TITLE
SiriusXM functionality

### PR DESCRIPTION
**Pull request by jplourde5**
This is the siriusXM function that I mentioned earlier.  Let me know if you are okay with adding it and I will update the documentation.

Usage 
/ROOM/siriusXM/{channel name}
or
/ROOM/siriusXM/{channel number}

Note: You must have at least one SXM channel in your Sonos Favorites

There is also a previous update that I made to the Apple Music documentation being included.

### CODE REVIEW

**Comment by jishi** [comment]
Are you sure that the SA_RINCON string is actually unique? Because for other services this is just a static placeholder that references the credentials that you can see at:

http://zone_player:1400/status/accounts

If they do reference a username (that is the case with username/password authenticated services), then that username can be extracted from there as well, without the need for a favorite in place. 

I have future plans at extracting this info at startup and provide it for querying for things like this.

**Comment by jishi** [comment]
Also, this is a merge request for master branch, not beta branch, which won't work since the master doesn't use promises, yet.

**Comment by jplourde5** [comment]
Nice. Let me play with the Account query.  

The RINCON prefix is consistent across all of the stations for a user, but you may be right about it being different for different users.  I have no way to know, looking at just my environment. What do you see as your prefix?

I also see RINCON for the Pandora metadata, but the number that immediately follows is a 3 instead of then number used for SiriusXM.  I'm guessing that RINCON is consistent, especially if you see it too, but the number I'm not too sure about.


Jim Plourde | VP Cloud Services

mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com | http://www.infor.com


________________________________________

**Comment by jishi** [comment]
Well, I don't have SiriusXM since I'm not in the US, but unless that RINCON string has a username or similar in it, I would say that it is just a service identifier, like for Spotify:

`SA_RINCON2311_X_#Svc2311-0-Token` 

This is basically 2311 = Spotify EU, and the 0 in Svc2311-0-Token references a specific account on your system (0 is always the first one). If I add a second Spotify account, that account would have another number than 0 in it.

Any info that you see in the /status/accounts page, is practically non-secret. It might even be possible to hardcode that SA_RINCON string in that case, like we have done with Spotify/appleMusic.

**Comment by jplourde5** [comment]
Okay, sounds like it needs to be captured then.  Not a show stopper to have to lean on Favorites.  Most people will probably have the needed Favorite there anyway.  I just don't like the "fine print" aspect.  But when you are working with unofficial "API's", tactics like this may sometimes be required. At the end of the day, the solution still works well.


Jim Plourde | VP Cloud Services

mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com | http://www.infor.com


________________________________________

**Comment by jishi** [comment]
Yeah, we can improve it over time when I get the accounts info retrieval in place. Howver, I think it's a bit crude to rely on this check to find Sirius favorites:

`item.uri.startsWith('x-sonosapi-hls:')`

It might match other providers that uses HLS streams as well. You should also look for a matching SA_RINCONxxxx with the numeric ID for sirius.

Also, I need a pull request for beta branch instead.

**Comment by jplourde5** [comment]
I thought that I had uploaded and pulled from beta, but apparently not.  I believe that I was in beta when I created the pull request but the defaults still fall back to master when you start a pull request.  New to using Gethub and still learning some of the interface nuances.  Corrected now.


[cid:image001.gif@01D1BBE6.BD37D4C0]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jplourde5** [comment]
BTW, are you in Linkoping by any chance?  Seems like I saw somewhere that you are in Sweden.


[cid:image001.gif@01D1BBFA.22D46CE0]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jishi** [comment]
No, I'm in Stockholm, the capital. 

The SA_RINCONxxxx number is actually based on a scheme where you have a service identifier for the service which usually appears in the current uri as sid=xxx (for spotify this is 9, for tunein this is 254, soundcloud 160 etc). 

This number is shifted 8 bits left, and then the 3 right-most bits are turned on, which basically is:

id * 256 + 7, so:

9 * 256 + 7 = 2311 (Spotify)
160 * 256 + 7 = 40967 (Soundcloud)

And so on. I'm not sure why they do this, but it seems consistent. Previously, the serialnum in the accounts page corresponded to the actual sid, but not anymore since they introduced multiple accounts per service. Now that is just an incremental number, but the sid is still visible in the uri's.

**Comment by jplourde5** [comment]
I’ve been to Linkopin a few times.  We have an office in Stockholm too, but I haven’t made it up there yet.

So are you saying that the xxxx will be consistent for every service, or did you say that it might vary by region?


[cid:image001.gif@01D1BC05.2CD0E100]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jishi** [comment]
Well, if we look at the example for spotify again:

`SA_RINCON2311_X_#Svc2311-0-Token`

the `SA_RINCON2311_` is gonna be consistent, for Spotify in most regions (spotify has another service ID for US though, but that's irrelevant)

The `X_#Svc2311-0-Token` is consistent for this service and the first account, but some services have specific data here that is discoverable from the /status/accounts page, usually a username or email in that case.

**Comment by jplourde5** [comment]
So should we try to see if we can go with the algorithm + order + account ID in the status/accounts page?

Another factor for Pandora is that I need the password in order to interact with Pandora.  I have the music playing already BTW.  I don’t see a way around this one unless the /status/accounts page reveals the password in the clear or even encrypted if the encryption is consistent with what the Pandora site expects.  But there is also a timestamp that is returned by the login and passed to subsequent calls, so I don’t think that having the encrypted password by itself will work.

Best case, I can retrieve the password (doubtful).

Worst case, need to store a password somewhere.  Where would the best place to store it be?


[cid:image001.gif@01D1BC09.82FDBE50]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jishi** [comment]
I think it would be easier if you could send me the info from your /status/accounts page via email, jayjay@grabbarna.se and I would be able to tell you how static the info is. It doesn't contain sensitive data, merely usernames if applicable.

**Pull request closed without merging**
