### PR TITLE
musicSearch

### PR DESCRIPTION
**Pull request by jplourde5**
The new music search and play functionality supporting Apple Music, Spotify, Deezer, and the local Sonos music library.  Include the full musicSearch.js service and updated documentation.  We may want to revert appleMusic back to its original form since this includes the same functionality and more.

### CODE REVIEW

**Comment by jplourde5** [comment]
Hi Jimmy, I'm about ready to push the echo-sonos enhancements.  Is there anything that needs to be changed here in order for you to merge it?

**Comment by jishi** [comment]
Okay, I'm back from vacation now. I was under the impression that we would abstract the searching into a "library" which was then used by all search actions (apple, spotify, deezer etc) but keep the old URL scheme. It will be confusing if we have two different search action for all services that would behave differently. Maybe we should flag this as experimental and plan for replacing the other versions later on if you want this merged now.

**Comment by jplourde5** [comment]
My thought was that we would revert appleMusic back to what it was or remove it.  The behavior for Apple, Spotify, Deezer, and the library are all the same, within their capabilities.  I've been testing for weeks and it is working well.  Working through echo-sonos testing right now and it is very close.

**Comment by jplourde5** [comment]
Testing is going well.  Chasing one odd issue with Deezer with one user.  Cleaned up siriusXM and musicSearch so that they retrieve the account info for the token from the Sonos /status/accounts instead of needing entries in Favorites or information in settings.json.  Reverted appleMusic back to what it was which will be useful for those wanting to play track and album IDs that they retrieve on their own. Updated the reademe documentation accordingly.

**Comment by jplourde5** [comment]
The issue with Deezer was that there are two versions, Standard and Elite, with some metadata differences.  Now supporting both.

**Comment by jplourde5** [comment]
Now that everything is working well, I'm cleaning up the code by breaking out the different music services into their own definition js file where each is easier to read, removes a ton of IFs, and makes it easier to add additional services. The definitions code is still loaded by musicSearch so that the play logic is in still one place and plays consistently.  musicSearch sits in the actions directory but I put the service definitions in a new directory in lib called music_services.

Some users were reporting problems with th json files being in actions because they were getting loaded by the http code. I moved them out of actions and into library. 

I've also done a good bit of work with the tokens and service type codes. I now go to status/accounts for the user ID when needed, calculate the service type code using the sid X 256 + 7, and I've created a means for discovering and setting a sid if it is different for a service in a different region.

I basically cleaned everything up.  I'm still mulling over a couple of potential items to shift out, and also continuing to test.  When ready, I'm going to close out this pull, create a new refreshed branch, drop in the changes, and create a new pull.

Let me know if you have any additional thoughts and/or observations.

**Comment by jishi** [comment]
Are we still gonna have /room/musicSearch/service/ or is it gonna be /room/service/ only? I think the latter is nicer, if possible.

**Comment by jplourde5** [comment]
Still /ROOM/musicsearch/SERVICE/TYPE/TERM

What has changed is just the organization of the code.  It is now much more readable and it is much easier to clone one of the service definitions and make the needed metadata and logic changes.  There is still common logic in musicSearch.js that would be duplicative and harder to maintain if separated.

I'll try to get this uploaded tonight and you can see what I'm talking about.

**Pull request closed without merging**
