### PR TITLE
feat: Elevenlabs TTS Provider

### PR DESCRIPTION
**Pull request by mgorsk1**
Adds Elevenlabs TTS AI powered provider. From Elevenlabs webpage:

```
Speech Synthesis
Unleash the power of our cutting-edge technology to generate realistic, captivating speech in a wide range of languages.
```

### CODE REVIEW

**Review by jishi — COMMENTED** [review]
This is a nice addition, just some minor comments on alternative coding styles. If you don't have time to fix it, I'm open to merge it as is.

The elevenlabs synthesize output was really nice, haven't heard of them before. The fact that it handles languages transparently makes it great when you have mixed languages.

**Comment by mgorsk1** [comment]
thanks @jishi for good feedback! I've refactored it per your remarks - feel free to retest and re-review ;)

**Comment by jishi** [comment]
Thank you. I don't have the means to test this myself, but it looks correct and I'm assuming it actually works for you.

**Comment by mgorsk1** [comment]
It's working, both me and Mr. T can confirm 🫡https://github.com/jishi/node-sonos-http-api/assets/5680655/a0752481-f825-403f-98c3-396e8233a465

**Comment by d6mck** [comment]
This is a great quality TTS addition to the library. Thanks for coding up.

**Pull request merged**
