### PR TITLE
Music Search and Play

### PR DESCRIPTION
**Pull request by jplourde5**
New function musicSearch supports search and play for Apple Music, Spotify, Deezer, Deezer Elite, and the local Sonos music library

### CODE REVIEW

**Comment by jplourde5** [comment]
Eliminated 99.9% of the contents of eliteDef.  eliteDef points to deezerDef with an init call that sets the song uri to the FLAC setting.

**Comment by jplourde5** [comment]
Eliminated the def and simply changed eliteDef to be equal to deezerDef with the unit call to set song output to FLAC.

**Comment by jplourde5** [comment]
Do you know when you may push the beta to main?  

Also, is there anything that you are waiting on to accept this pull request?

**Comment by jishi** [comment]
I have a few issues that I want to resolve before moving on from beta. Sleep doesn't work, and radio titles doesn't populate state correctly. 

I have just been super busy with other stuff so I haven't had time to verify your pull request, sorry about that.

**Comment by jplourde5** [comment]
No worries.  Let me know if I can help with any of the other troubleshooting.

**Comment by jishi** [comment]
I have been trying to verify the spotify functionality (since that is the only one I'm using), but it insists on selecting sid=12 instead of sid=9 which is used in Sweden/Europe.

I found that there is some sort of geo-ip lookup, but couldn't easily find which regions relate to which ID. There is references to ./lib/sids.json but that file doesn't seem to be part of the commit?

It would be possible to find out which services and IDs that are available on the system in question using a UPnP call to GetAvailableServices, that could be a big improvement. With that, it would be possible to find out service details using more canonical names.

**Comment by jplourde5** [comment]
The sid is 12 in the US.  I created a means for discovering what the SID is based on a specified example in the Sonos Favorites.

.../ROOM/musicsearch/spotify/setsid/name_of_spotify_song_in_sonos_favorites

But, this is a bit of a kludge and if there was a way to know what they all are in advance by country code, that would be a better solution.

**Comment by jishi** [comment]
Hm, but that's weird. I have Spotify favorites so I would have assumed it found out the correct sid. I'll look into it some more.

**Comment by jplourde5** [comment]
It doesn't go searching automatically to check the SIDs because it wouldn't know which service was used for a favorite.  

You correct the SID by issuing the setsid command (below), it sets the SID for the specified service to the same SID as the specified song, writes the SIDs out to a sids.json file in lib, and reloads that file on startup.  Save and restore the the sids.json file if you blow away everything with an update. 

.../ROOM/musicsearch/spotify/setsid/name_of_spotify_song_in_sonos_favorites

**Comment by jishi** [comment]
I think I merged an older version of this branch by mistake, so I might as well merge it and we'll try to resolve the issues together, it doesn't affect anything else, I hope.

**Comment by jplourde5** [comment]
I checked the last change that I made and it is there, so I think that you got the latest.

**Pull request merged**
