### PR TITLE
CA option for HTTPS

### PR DESCRIPTION
**Pull request by stevenlevin**
Checks for existence of ca in https settings and sets the option
accordingly

### CODE REVIEW

**Comment by jishi** [comment]
This is to, somehow allow self signed certificates without warnings, but would also be required on the client as well, or am I mistaken?

I'm a bit reluctant to extend the HTTPS support further, since my recommendation is still to have a public nginx in front of the http api for public access. That already gives you all of these options and is much better supported. Also gives you the possibility to have local unauthenticated requests, but authenticated for internet-facing requests.

Also, since let's encrypt certificates are free, those are also an option that sort of mitigates the need for self-signed certs on most cases.

**Comment by stevenlevin** [comment]
No this is actually to get let's encrypt certificates to work with AWS Lambda services.  With out this option Lambda will report back in the logs: { [Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } 

I understand your recommendation to have this API running behind a public nginx.  I guess I will have to look into this configuration.

**Comment by jishi** [comment]
I'm confused. Unless you are using client certificates that are issues by an "unknown" CA, that could be specified here, this option doesn't make sense to me.

Intermediate certificates should go into the cert option,  as regular PEM formatted certificates. 

If this is calls FROM lambda, against the API, and lambda doesn't trust let's encrypt certificates, It seems like you actually need to specify the let's encrypt root certificate when making the request in your lambda, not in the HTTP API... because it doesn't seem very secure if any server can just include the root CA to make any client happy about it?

**Comment by stevenlevin** [comment]
I combined the intermediate into the cert option as you said and that resolved my issue.  Sorry I misinterpreted how the CA option was to be used for a node https server.  Thanks for teaching me something new.  Cheers!

**Pull request closed without merging**
