### PR TITLE
play tunein radio, docker build file

### PR DESCRIPTION
**Pull request by sseiber**
- action for playing tunein radio
   `host://room/tunein/play/{stationid}`

 - Docker build file

### CODE REVIEW

**Comment by sseiber** [comment]
Note, this is only the Tunein radio playback action. This does not include the service definition that supports music searchings on the Tunein service.

**Comment by jishi** [comment]
Could you remove the Dockerstuff (maintained by separate repo) and the deletion of sample files from this PR? And also add some description to the README. 

You also use the action `play`, while the other ones use `now`, `queue` and `next`. Maybe we want to use only `now` for conformity? Or no action at all, since radios can't be queued.

**Comment by sseiber** [comment]
I'll make those changes.

Regarding the play action,I was following your Pandora example. Now, queue, and next all deal with the queue so perhaps something else is bettter? I think there should be some action for broadcast streamers - perhaps "tune". Let me know if you have a preference between that or no action.

**Comment by jishi** [comment]
Aha, forgot about those since they were contributed. Then I'm fine with the `play` keyword. Given that Pandora also has thumbsup/down it makes some sense to have a keyword for playback.

**Comment by sseiber** [comment]
I've got a new branch with the minimal changes so I'll close this PR and create a new one.

**Pull request closed without merging**
