### PR TITLE
added support for https and basic auth

### PR DESCRIPTION
**Pull request by edanuff**
Added the ability to enable https connections and http basic authorization to make this safer to use from the Internet.  These can be specified via 'https', 'auth', 'name', and 'pass' in settings.json.

### CODE REVIEW

**Comment by jishi** [comment]
Sorry about the delay on commenting this. What is your take on builtin approach vs using nginx as a reverse proxy for this? I somewhat feel that this is outside the scope of a normal user, and if you are able to get your hands on a certificate you are able to setup nginx as well? 

Basic auth on the other hand might be another matter. 

I'm a bit undecisive at the moment, what's your thoughts?

**Comment by tlc** [comment]
As a user looking for this functionality, I would appreciate not needing to run nginx.  

The mods seem modest in size and optional.  If it's too much for the normal user, they don't have to use the option.  There are scripts out there on how to get a certificate.

**Comment by edanuff** [comment]
Setting up nginx for this seems like a lot of extra work.

**Comment by jishi** [comment]
Okay, great feedback guys. I will merge it, but I need to resolve the conflicts first (unless @edanuff can update the pull request).

**Comment by BrakesTilApex** [comment]
...this is a feature I'd love to see. Total noob but I've managed to cook up a self-signed cert and just need to figure out how to put it to use! Great work, really.

**Comment by edanuff** [comment]
Resolved conflicts, ready for merge

**Comment by dohall** [comment]
would definitely like to see this go through, any update on it?

**Comment by jishi** [comment]
Hi, sorry for not getting back on this, I was planning on doing some modifications before merge but I never got around to it. Given that people start exposing their installations publicly because of the Alexa integration, this is very important to get in place.

If you can consider doing some changes, I would merge it straight up. I would like:

No boolean flags for toggling https/auth. Basically, I would like it to be something like this:

settings.json
```
{
	https: {
		key: '/path/to/private.key',
		cert: '/path/to/cert.pem'
	},
	auth: {
		username: 'admin',
		password: 'password'
	}
}

alt: (for PKCS#12)
{
	https: {
		pfx: '/path/to/cert.pfx'
	},
	auth: {
		username: 'admin',
		password: 'password'
	}
}
```

And check for the existence of configuration, rather than a boolean flag? I think that it is simpler to comprehend. It is also nice to have the cert files configurable, if you share them between multiple services for some reason. 

Does this make sense?

**Comment by dohall** [comment]
Yeah, I need this for that exact reason (Alexa). Your requests seem logical to me. If @edanuff doesn't beat me to it, I'll work on these changes.

**Comment by jishi** [comment]
I merged dohalls branch with these changes.

**Pull request closed without merging**
