### PR TITLE
Add a landing page

### PR DESCRIPTION
**Pull request by maddox**
This adds a page at the root so it responds with something. It advertises what it is, and the API endpoints available.

screen shot 2016-08-29 at 4 53 24 pm

### CODE REVIEW

**Comment by jishi** [comment]
Hi, great add! But I would prefer to put this in the beta instead, I will soon replace the master version with the beta since it is greatly improved. 

Also, there is a swagger-UI with documentation and a simple sandbox already included, but it might not be completely up to date. Maybe consider linking to that and getting that up to speed would be more useful as documentation?

**Comment by maddox** [comment]
> I will soon replace the master version with the beta since it is greatly improved

Oh, I wasn't aware of that.

I'll check out the branch and open a pull against that. Thanks!

> Maybe consider linking to that and getting that up to speed would be more useful as documentation

Oh that's a great idea.

**Comment by maddox** [comment]
What's new/changed with the `beta` branch? I couldn't resolve anything from the README. It looks unchanged.

**Comment by maddox** [comment]
Closing this to re-open against the `beta` branch.

**Comment by jishi** [comment]
The beta branch uses the completely rewritten base library which is promise-based. This allowed me to design all HTTP endpoints to "wait" until the action has finished which id didn't before, and the say/sayall commands are greatly improved and also wait for the announcement to finish which makes it easy to chain several commands.

**Comment by jishi** [comment]
It still has a few bugs, the major one being that state info for radio stations isn't correct. I haven't had time to correct it yet.

**Comment by maddox** [comment]
> This allowed me to design all HTTP endpoints to "wait" until the action has finished which id didn't before

Oh, this is nice. I actually ran into issues with this. I have an iPad dash in my kitchen that I put a Sonos controller on, based on this project. It used to control my old [itunes-api](https://github.com/maddox/itunes-api) setup. But yeah, I had basically sleep for a second before updating state because the request completes immediately.

The dash is based on http://dashing.io. Here's the widget:

screen shot 2016-08-30 at 10 03 52 am

I'm not sure what the beta looks like, but what would be even more convenient, is if state was returned after every action. That'd make it even faster to update everything. Because a second request wouldn't have to be made to update state after the action has completed. This is how I did it in itunes-api. That way the client gets an updated snapshot of the current state after every action taken.

**Comment by jishi** [comment]
I think there is an easier solution for you. You can use the webhook to update state instead, that would reflect changes from other controllers as well, if the system running the widget can receive http requests.

Or create your own layout on top of the sonos-web-controller, that one uses websockets to update content instantly.

**Comment by maddox** [comment]
> I think there is an easier solution for you. You can use the webhook to update state instead

I thought about that, considering the current state of `master`.

But I think it'd be more appropriate for the request to block until it's actually complete, rather than being fully async. So the client can trust that the next request will get back the correct state.

And my other suggestion of returning the current state as a response to the request is proper REST etiquette. Especially since right now, the response is just empty.

My issue with the webhook is that, for this scenario, it's just added infrastructure and setup that seems unnecessary in a REST environment.

**Comment by jishi** [comment]
The beta branch always return a JSON response, but right now it just says "OK" which isn't really helpful. 

However, all actions to the Sonos players are async by nature, meaning that even if you have invoked `nextTrack` successfully, doesn't mean that the state of the players has changed yet (this is reported as an event request from the Sonos player), meaning that I would return stale data anyway as response. It is very tricky to get this right since there is no real correlation between my action against a sonos player, and the evented data in return. When multiple people control multiple players simultaneously, it becomes impossible to handle.

And not to mention the fact that control from an official Sonos controller won't update your widget. 

But I suggest you check the mobile view of the web-controller (using the /m path), that is basically the same view as your widget (but with a volume control). You could even just use that that as a backend to provide the websocket for your regular dash, if necessary (I think). It might give you some ideas.

**Comment by maddox** [comment]
> However, all actions to the Sonos players are async

Ahhhh.

> And not to mention the fact that control from an official Sonos controller won't update your widget

Yup. It's just polling right now.

Yeah, I suppose you're right. The widget has enough responsibility that setting up a web hook is probably worth the effort.

**Pull request closed without merging**
