### PR TITLE
True isolation

### PR DESCRIPTION
**Pull request by scottlow**
This change set adjusts the functionality of `isolate` as follows:

The call for isolate is now `PlayingRoom/isolate/PlayerToIsolate`. In other words, a user must first specify a room that's currently playing music (`PlayingRoom`) and a player to isolate (`PlayerToIsolate`). When this is called, the music from `PlayingRoom` will be piped to `PlayerToIsolate` and all other players except for `PlayerToIsolate` will stop playing. If `PlayingRoom` is not playing music, nothing will happen.

The downside with the approach used here is the fact that any groups the user has created will not be preserved due to the loop that calls `becomeCoordinatorOfStandaloneGroup()` in `performIsolate()`. There is a comment thread on #37 discussing other approaches to circumnavigate this issue.

### CODE REVIEW

**Comment by jishi** [comment]
Well... I'm not sure if this is the right approach to be honest. To start with, these command shouldn't require two different players as arguments, since it would be fine by one. It should also replicate the official behavior, which I'm not sure how it works right now. You could easily try this by when grouped, click on the group button and uncheck all players that you want to leave. 

Do you have a specific scenario where you would find the isolate function useful? A lot of these operations would actually be possible to do with presets, which in some scenarios offers even better functionality.

**Comment by scottlow** [comment]
My thought was to allow the choice of a source player just in case a user had two groups playing and only wanted to isolate one. (It would be the equivalent of picking which group to ungroup in the Sonos GUI controller).

I only have two players in my place, so I'm not sure what the official behaviour is when there are multiple groups. 

I'm using these changes combined with https://github.com/rgraciano/echo-sonos to create commands like "Alexa, play the master bedroom in the living room". If that's possible to do with presets, however, I could just do that. 

Let me know if you want this done a different way, or feel free to close it if you don't see a need.

**Comment by jishi** [comment]
I'm not really following you... if you want to isolate a player, don't you want to disregard which group it belongs to, and promote it to coordinator and ungroup all other players? Still don't see why you need to reference a second player in that scenario.

I'm gonna run some tests at home and see what the expected behavior is, so we know. 

If you want to control grouping using voice commands like in your example, then the preset is not a good fit. Preset would be more like pre-defined settings, and using echo you would tell it to apply a specific configuration in that case. It would still be useful though, but not as flexible as your example.

**Comment by scotta1029** [comment]
Hi, I appear to have a problem. I program in crestron so this is a bit outside my area, when trying to install i am getting, "no such file or directory, open C:\users......json" Any ideas? 

thanks

**Comment by jishi** [comment]
@scotta1029 Please create a separate issue with a bit more info instead, since it isn't related at all to this pull request.

**Comment by jishi** [comment]
I wanted to revisit this once again:

Have I understood it correctly that you want to take a player, from a group, and continue playback on only that device? Meaning, this would be equivalent to opening up the group view in the official controller, and uncheck all other players except the one that you want to isolate?

And one downside of this, is that all other players would be set as standalone groups, and not kept as a group and retain the same queue, and position etc? (a player remembers it's last queue when grouped, if it isn't the coordinator or becomes promoted to the coordinator, which sometimes are preferable).

It would perhaps be possible to promote another player as coordinator, then leave the group and pause the remaining group and continue playback on the isolated device. It does however go against the normal procedure and might conflict with the way people expect it to be.

**Comment by scottlow** [comment]
@jishi Sorry it's taken me so long to reply to this. Yes, that is the scenario I was trying to implement with this. In this PR, I also included the option of choosing which room to isolate on which player. (This would allow for voice commands with Amazon Echo for something along the lines of "Alexa, play what's on in the living room in the kitchen only")

I do admit that this may be a little counter-intuitive to some. I've got it working at home now and I like using it, so I thought I'd share this in case there are others wanting to do the same. Perhaps `isolate` isn't the right command name to use here though.

**Comment by jishi** [comment]
Is this still something people are interested in? I'm not really sure what the use case was here, TBH.

**Comment by jishi** [comment]
Closing since functionality unclear.

**Pull request closed without merging**
