### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by jishi** [comment]
I've actually already had a Dockerfile and chose to remove it since people kept coming to me for support about docker. I would prefer if someone else maintained any published Docker image in their own repo (either via fork, or using a sub repo linking). If someone were to maintain that, I would gladly link to that repo and instructions for Docker for people that are looking for it.

**Comment by chrisns** [comment]
That's annoying (for you).
Would you be willing to setup a webhook in github from your master branch so I can at least rebuild when you push a new version?

**Comment by chrisns** [comment]
Amazing. do you have a public GPG key or another way I can securely give you the webhook url to plug into github?

**Comment by chrisns** [comment]
and/or a dockerhub account and I'll add you as a collaborator to the image?

**Comment by chrisns** [comment]
Updated so this PR is just a readme reference.
If you could let me know how to give you the webhook that'd be ace

**Comment by jishi** [comment]
I created a GPG key pair, here is the public key: https://gist.github.com/jishi/3274944991aa1e054a5bfeae25ac026c

I think you get the email in that key, just sen the encrypted url via email or similar.

**Comment by chrisns** [comment]
Hey @jishi I just updated the docker image and added in cross arch builds and build with github actions, but in doing so have broken the webhook we setup. i've setup @dependabot to do it nightly for now with a git submodule, at some point it might be good to wire something up again to get a push from your webhook.
mostly letting you know so you will know to expect that webhook to fail now.

**Pull request merged**
