### PR TITLE
Fixes for Swagger and resumeall

### PR DESCRIPTION
**Pull request by bobby-brennan**
Very cool project, just finished setting it up.

Two fixes here:
* Swagger was using /sonos in paths but I don't see that being used
* resumall was checking if pauseState == "PLAYING" before calling play(), resulting in a no-op

Let me know if you have any questions!

### CODE REVIEW

**Comment by jishi** [comment]
Hi, I had forgot about this pull request.

resumeall is supposed to be used in combination with pauseall, so what it actually is supposed to check is the previous state. If it works without first calling pauseall, then this is a mistake on my end. 

What you are actually expecting is something like "playall", that would invoke play on all coordinators in your system. This can give very unexpected results and might not be desireable. I usually promote using presets for this instead, so you can actually control volume etc before blindly hitting play.

**Comment by bobby-brennan** [comment]
I thought that might be the case.  Still I think [this line](https://github.com/jishi/node-sonos-http-api/pull/120/files#diff-c01d75932dd0a3c5eafdff7f7c622a00L39) needs to change?

```js
if (pauseState[uuid] == "PLAYING") {
```
should be
```js
if (pauseState[uuid] != "PLAYING") {
```

Let me know and I can break out a separate PR

**Comment by jishi** [comment]
Well, no, since it should only resume players that _was_ playing, when they were paused. pauseState isn't the current state, it is the state that was active when it got paused.

I just think it's a general misunderstanding what "resumeall" actually is that causes the confusion.

**Comment by bobby-brennan** [comment]
Ahh I get it now. Thanks for clarifying

Bobby Brennan
bobby.brennan@gmail.com

**Pull request closed without merging**
