### PR TITLE
Updated say.js

### PR DESCRIPTION
**Pull request by brammittendorff**
The google TTS does not work anymore i created a own TTS for your service. Have fun!

### CODE REVIEW

**Comment by potherca** [comment]
:+1: I was having problems with the Google TTS not working... This would be a nice solution.

**Comment by jishi** [comment]
I like the initative, but I'm not really comfortable with someones self-hosted TTS-service in the long run. I can merge this right now since google is completely broken, but in the long run I aim for implementing voicerss with support for a paid account.

**Comment by brammittendorff** [comment]
I can understand, on mac it is easy to use the "man say" command on linux you can use festival but you need to encode it to mp3. On linux it will be lame encoding and on mac you can install ffmpeg. So you can serve your file locally. But on windows you will need an other approach. It takes me a while to find all of this out. Are you interested in a patch including local options for TTS?

**Comment by jishi** [comment]
Well, I was mainly talking about using the online service http://www.voicerss.org/ since it would be OS agnostic. It also has a paid option for those who might hit the limits of the free account, and this also gives more confidence that the service would stay up. It also has very natural speech compared to other solutions I've tried.

**Comment by brammittendorff** [comment]
Well the natural speech is possible by MBROLA voices within festival, i think voicerss uses it to. I am implementing a nice api with good voices, bitrate and other options very soon. This weeks planning will be multiple languages with parameters to choose your own voice. You are free to decide what suits the best for you. My service will be free, and my plans are to keep it online as long as i can (hopefully forever).

**Comment by jishi** [comment]
Well, any online service is dependent on some sort of cost, both money- and time wise. Hopefully you will manage to keep this running for as long as possible, but from experience these thing rarely keeps on living without any sort of economic backing, sorry if I'm being pessimistic. We could still use it as a default for people that doesn't want sign up for an api-key to voicerss though.

**Comment by potherca** [comment]
Would it make sense to extract the TTS provider so that the user can choose which one to use?
That would also make it a lot less painful to add/change a provider in case whichever solution is used goes down...

**Comment by jishi** [comment]
@potherca Sure, that makes sense, but we have to keep in mind that a lot of users aren't technical in this regard, so it must be considered optional and work out of the box.

**Comment by potherca** [comment]
Absolutely agree. 

As those non-technical users will hold you responsible if things don't work out-of-the-box, it's only logical that you get final say in which TTS provider the product comes packaged with. But if at all possible, being able to connect other services could also be a huge win for those non-technical user if things are (temporarily) unavailable.

But if you're open to having a layer of abstraction to inject a TTS provider into the `say` function, I'm sure @brammittendorff and/or myself wouldn't mind taking a stab at this...

**Comment by devployment** [comment]
>Well, any online service is dependent on some sort of cost, both money- and time wise. Hopefully you will manage to keep this running for as long as possible, but from experience these thing rarely keeps on living without any sort of economic backing, sorry if I'm being pessimistic. We could still use it as a default for people that doesn't want sign up for an api-key to voicerss though.

Well put and looks like it didn't take too long to prove you're right. At least to me http://www.nerd.host/tts/ appears to be down.

@potherca, @jishi, any thoughts on abstracting the TTS provider?

**Comment by potherca** [comment]
@brammittendorff:

> http://www.nerd.host/tts/ appears to be down.

@devployment: Currently [the url is hardcoded](https://github.com/jishi/node-sonos-http-api/blob/master/lib/actions/say.js#L212). The shortest route would be add an entry to a `config.json` and provide the user with a list of options that comply to the Google API (which will be few). 

The _cleanest_ route would be to have a wrapper object for each TTS (as every server will have a separate API) to provide a uniform API for the code in `say.js` to call. Every new option (different TTS server) would require a new wrapper. There is [a library that does something like this](https://github.com/G33kLabs/node-tts-speak) but I can't comment on how stable/good it is (or even how it works).

The only _truly bulletproof_ solution would be to ship a TTS server (like [this java implementation](https://github.com/marytts/marytts)) with the project but personally, I think that might be overkill (and cause a whole new specific set of problems for users and maintainers).

An in-between-ish solution _could_ be to try and use native TTS's (like `say` on OSX) but that would most likely still require wrappers to mitigate the different on different Operating Systems.

Thoughts?

**Comment by devployment** [comment]
@potherca, I was aware of the hard coding. But as I see you already have directions about the issue. :)

Just flew over the linked library (https://github.com/G33kLabs/node-tts-speak) but IMHO it looks simple enough to evaluate goodness/stability fairly easy I think. If somebody would really like to go down the native route it might be good place to implement it there as well if possible.

Everything else might be pure overkill for this API project as you said. I will play around a bit with the library to see how it works as the whole TTS stuff is pretty new to me.

**Comment by devployment** [comment]
Looks like the Google API is still reachable somehow. Maybe a good first fix here.

https://translate.google.com/translate_tts?ie=UTF-8&q=this%20is%20a%20simple%20test,%20right?&tl=en&client=foo

**Comment by jishi** [comment]
Seems like the client=foo parameter bypasses the captcha. I wouldn't expect that to work for very long, unfortunately.

And even though a provider-based system would be nice, I think it might be overengineering to allow people implementing their own providers given the low code contribution I actually receive on this project. However configurable options (meaning, choose between a few well known TTS-services) would be useful.

**Comment by potherca** [comment]
I also seem to remember Bing had (has?) a TTS API somewhere that hasn't (yet) been boxed of... I'll post back here if I manage to find it again :smiley:

**Comment by jishi** [comment]
Maybe you guys could continue this discussion in the voicerss-ticket? I feel like this pull request isn't the right place. https://github.com/jishi/node-sonos-http-api/issues/97

**Pull request merged**
